language: php
php:
  - 5.5
  - 5.4
  - 7
  - hhvm
script: phpunit tests/ProductTest.php
script: phpunit tests/UserTest.php
script: phpunit tests/AttendanceTest.php
script: phpunit tests/StudentTest.php

